//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Arnaud Verrier on 28/09/2018.
//  Copyright (c) 2018 tagattitude. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
    func fetchOrders(request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore
{
    var firstName: String { get set }
    var lastName: String { get set }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
    var presenter: ListOrdersPresentationLogic?
    var worker: ListOrdersWorker?
    var orderWorker: OrdersWorker?
    
    var firstName: String = "Arnaud"
    var lastName: String = "Verrier"
    
    // MARK: Do something
    
    
    
    func fetchOrders(request: ListOrders.FetchOrders.Request)
    {
        orderWorker?.fetchOrders {
            [weak self] orders in
            
            let response = ListOrders.FetchOrders.Response(orders:orders);
            self?.presenter?.presentFetchOrder(response: response)
        }
    }
}
