//
//  OrderModels.swift
//  CleanStore
//
//  Created by Arnaud Verrier on 28/09/2018.
//  Copyright (c) 2018 tagattitude. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Order
{
    var id: String
    var date: Date
    var email: String
    var firstName: String
    var lastName: String
    var total: NSDecimalNumber
}
