//
//  CreateOrderInteractorTests.swift
//  CleanStore
//
//  Created by Arnaud Verrier on 01/10/2018.
//  Copyright (c) 2018 tagattitude. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class CreateOrderInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CreateOrderInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCreateOrderInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCreateOrderInteractor()
  {
    sut = CreateOrderInteractor()
  }
  
  // MARK: Test doubles
  
  class CreateOrderPresentationLogicSpy: CreateOrderPresentationLogic
  {
    var presentExpirationDateCalled = false
    func presentExpirationDate(response: CreateOrder.FormatExpirationDate.Response) {
        presentExpirationDateCalled = true
    }
    
    var presentInformationCalled = false
    func presentInformation(response: CreateOrder.Information.Response) {
        presentInformationCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentInformationWhenAutoInformationWithAutoInformation()
  {
    // Given
    let spy = CreateOrderPresentationLogicSpy()
    sut.firstName = "Arnaud"
    sut.lastName = "Verrier"
    sut.presenter = spy
    
    // When
    sut.autoFormatInformation()
    
    // Then
    XCTAssertTrue(spy.presentInformationCalled, "autoFormat(request:) should ask the presenter to format the auto format")
  }
    
    func testDontPresentInformationWhenAutoInformationWithoutAutoInformation()
    {
        // Given
        let spy = CreateOrderPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        sut.autoFormatInformation()
        
        // Then
        XCTAssertFalse(spy.presentInformationCalled, "autoFormat(request:) should not ask the presenter to format the auto format because no information")
    }
}
