//
//  CreateOrderPresenterTests.swift
//  CleanStore
//
//  Created by Arnaud Verrier on 01/10/2018.
//  Copyright (c) 2018 tagattitude. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class CreateOrderPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CreateOrderPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCreateOrderPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCreateOrderPresenter()
  {
    sut = CreateOrderPresenter()
  }
  
  // MARK: Test doubles
  
  class CreateOrderDisplayLogicSpy: CreateOrderDisplayLogic
  {
    var displayExpirationDateCalled = false
    func displayExpirationDate(viewModel: CreateOrder.FormatExpirationDate.ViewModel) {
        displayExpirationDateCalled = true
    }
    
    var displayAutoInformationCalled = false
    func displayAutoInformation(viewModel: CreateOrder.Information.ViewModel) {
        displayAutoInformationCalled = true
    }
  }
  
  // MARK: Tests
  func testDisplayAutoInformationCalledWhenAutoFormat()
  {
    // Given
    let spy = CreateOrderDisplayLogicSpy()
    sut.viewController = spy
    
    // When
    sut.presentInformation(response: CreateOrder.Information.Response(firstName: "Arnaud", lastName: "Verrier"))
    
    // Then
    XCTAssertTrue(spy.displayAutoInformationCalled, "presentInformation(response:) should ask the view controller to display the information")
  }
}
