//
//  CreateOrderViewControllerTests.swift
//  CleanStore
//
//  Created by Arnaud Verrier on 01/10/2018.
//  Copyright (c) 2018 tagattitude. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class CreateOrderViewControllerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: CreateOrderViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        window = UIWindow()
        setupCreateOrderViewController()
    }
    
    override func tearDown()
    {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCreateOrderViewController()
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "CreateOrderViewController") as? CreateOrderViewController
    }
    
    func loadView()
    {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    class CreateOrderBusinessLogicSpy: CreateOrderBusinessLogic, CreateOrderDataStore
    {
        var shippingMethods: [String] = []
        
        var firstName: String? = "Arnaud"
        var lastName: String? = "Verrier"
        
        var formatExpirationDateCalled = false
        func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request) {
            formatExpirationDateCalled = true
        }
        
        var autoFormatNameCalled = false
        func autoFormatInformation() {
            autoFormatNameCalled = true
        }
    }
    
    func testAutoFormatIsCalledWhenCreateOrderStarted()
    {
        // Given
        let spy = CreateOrderBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.autoFormatNameCalled, "ViewDidLoad() should try to auto format data")
    }
}
